item { 
	name:'Play/Pause'
	id:1
}
item { 
	name:'Volume Up'
	id:2
}
item { 
	name:'Volume Down'
	id:3
}
item { 
	name:'Fast_Forward'
	id:4
}
item { 
	name:'Rewind'
	id:5
}
item { 
	name:'Full_Screen'
	id:6
}
